include: package:lint/strict.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    # For Freezed
    invalid_annotation_target: ignore
    always_declare_return_types: error
    constant_identifier_names: error
    use_build_context_synchronously: error
    parameter_assignments: error
    depend_on_referenced_packages: error

linter:
  rules:
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
    use_super_parameters: true