name: gradu_go
description: "A hub for graduates benefits"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  url_launcher: ^6.2.6
  transparent_image: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  card_swiper: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/launcher_icon.png
    - assets/images/company_logo.png
    - assets/images/digital_id_card_back.jpg
    - assets/images/digital_id_card_front.jpg
    - assets/images/email_icon.jpg
    - assets/images/facebook_icon.png
    - assets/images/instagram_icon.png
    - assets/images/maps_icon.png
    - assets/images/phone_icon.png
    - assets/images/ticket_icon.png
    - assets/images/whats_icon.png
